# -*- coding: utf-8 -*-
"""Accuracy_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fIrWUQQhD_HhvXNy-duuSpe1ukmrYJEx
"""

import pandas as pd

df1 = pd.read_csv('target.csv')
df2 = pd.read_csv('non_target.csv')

x = df1['i']

y1 = df1['0.06']
y2 = df1['0.12']
y3 = df1['0.18']

plt.title("NI-FGSM - Target Accuracy") ### TI-FGSM NI-FGSM MI-FGSM
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")
plt.plot(x, y1, "o-",label="e = 0.06")
plt.plot(x, y2, "o-",label="e = 0.12")
plt.plot(x, y3, "o-",label="e = 0.18")

plt.legend()
plt.show()

y4 = df2['0.06']
y5 = df2['0.12']
y6 = df2['0.18']

plt.title("NI-FGSM - Non-Target Accuracy") ### TI-FGSM NI-FGSM MI-FGSM
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")

plt.plot(x, y4, "o-",label="e = 0.06")
plt.plot(x, y5, "o-",label="e = 0.12")
plt.plot(x, y6, "o-",label="e = 0.18")

plt.legend()
plt.show()

DI_target = pd.read_csv('DI_target.csv')
NI_target = pd.read_csv('NI_target.csv')
MI_target = pd.read_csv('MI_target.csv')
TI_target = pd.read_csv('TI_target.csv')

X1 = DI_target['i']
X2 = NI_target['i']
X3 = MI_target['i']
X4 = TI_target['i']

Y1 = DI_target['0.06']
Y2 = NI_target['0.06']
Y3 = MI_target['0.06']
Y4 = TI_target['0.06']

plt.title("Target Accuracy(epsilon = 0.06)")
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")

plt.plot(X1, Y1, "o-",label="DI-FGSM")
plt.plot(X2, Y2, "o-",label="NI-FGSM")
plt.plot(X3, Y3, "o-",label="MI-FGSM")
plt.plot(X4, Y4, "o-",label="TI-FGSM")

plt.legend()
plt.show()

DI_non_target = pd.read_csv('DI_non_target.csv')
NI_non_target = pd.read_csv('NI_non_target.csv')
MI_non_target = pd.read_csv('MI_non_target.csv')
TI_non_target = pd.read_csv('TI_non_target.csv')

X5 = DI_non_target['i']
X6 = NI_non_target['i']
X7 = MI_non_target['i']
X8 = TI_non_target['i']

Y5 = DI_non_target['0.06']
Y6 = NI_non_target['0.06']
Y7 = MI_non_target['0.06']
Y8 = TI_non_target['0.06']

plt.title("Non-Target Accuracy(epsilon = 0.06)")
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")

plt.plot(X5, Y5, "o-",label="DI-FGSM")
plt.plot(X6, Y6, "o-",label="NI-FGSM")
plt.plot(X7, Y7, "o-",label="MI-FGSM")
plt.plot(X8, Y8, "o-",label="TI-FGSM")

plt.legend()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df1 = pd.read_csv('target.csv')
df2 = pd.read_csv('non_target.csv')

x = df1['i']

y1 = df1['0.06']
#y2 = df1['0.12']
#y3 = df1['0.18']

plt.title("DI-FGSM - Target Accuracy") ### TI-FGSM NI-FGSM MI-FGSM
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")
plt.plot(x, y1, "o-",label="e = 0.06")
#plt.plot(x, y2, "o-",label="e = 0.12")
#plt.plot(x, y3, "o-",label="e = 0.18")

plt.legend()
plt.show()

y4 = df2['0.06']
#y5 = df2['0.12']
#y6 = df2['0.18']

plt.title("DI-FGSM - Non-Target Accuracy") ### TI-FGSM NI-FGSM MI-FGSM
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")

plt.plot(x, y4, "o-",label="e = 0.06")
#plt.plot(x, y5, "o-",label="e = 0.12")
#plt.plot(x, y6, "o-",label="e = 0.18")

plt.legend()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df1 = pd.read_csv('DI_target.csv')


x = df1['i']

y1 = [1.875, 2.875, 5, 10.625, 16, 26.875]
#y1 = df1['0.06']
#y2 = df1['0.12']
#y3 = df1['0.18']

plt.title("DI-FGSM - Final Target Accuracy") ### TI-FGSM NI-FGSM MI-FGSM
plt.xlabel("iterations")
plt.ylabel("Accuracy(%)")
plt.plot(x, y1, "o-",label="e = 0.18")
#plt.plot(x, y2, "o-",label="e = 0.12")
#plt.plot(x, y3, "o-",label="e = 0.18")

plt.legend()
plt.show()